-- Sesi tracking pendakian dan titik GPS untuk pemantauan keselamatan.
CREATE TABLE IF NOT EXISTS public.hiking_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at TIMESTAMPTZ,
  last_point_at TIMESTAMPTZ,
  last_latitude DOUBLE PRECISION,
  last_longitude DOUBLE PRECISION,
  distance_km DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (distance_km >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.hiking_track_points (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID NOT NULL REFERENCES public.hiking_sessions(id) ON DELETE CASCADE,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  accuracy_meters DOUBLE PRECISION,
  location GEOGRAPHY(POINT, 4326) GENERATED ALWAYS AS (
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
  ) STORED
);

CREATE INDEX IF NOT EXISTS idx_hiking_sessions_user_started
  ON public.hiking_sessions (user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_hiking_sessions_active
  ON public.hiking_sessions (status) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_hiking_track_points_session_time
  ON public.hiking_track_points (session_id, recorded_at);
CREATE INDEX IF NOT EXISTS idx_hiking_track_points_location
  ON public.hiking_track_points USING GIST (location);

ALTER TABLE public.hiking_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hiking_track_points ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own hiking sessions" ON public.hiking_sessions;
CREATE POLICY "Users can view own hiking sessions"
  ON public.hiking_sessions FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can create own hiking sessions" ON public.hiking_sessions;
CREATE POLICY "Users can create own hiking sessions"
  ON public.hiking_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own hiking sessions" ON public.hiking_sessions;
CREATE POLICY "Users can update own hiking sessions"
  ON public.hiking_sessions FOR UPDATE
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can view own hiking points" ON public.hiking_track_points;
CREATE POLICY "Users can view own hiking points"
  ON public.hiking_track_points FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.hiking_sessions s
    WHERE s.id = session_id AND s.user_id = auth.uid()
  ));
DROP POLICY IF EXISTS "Users can create own hiking points" ON public.hiking_track_points;
CREATE POLICY "Users can create own hiking points"
  ON public.hiking_track_points FOR INSERT
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.hiking_sessions s
    WHERE s.id = session_id AND s.user_id = auth.uid()
  ));

-- Backoffice admin membaca tabel menggunakan Supabase service_role.
-- Service role melewati RLS; jangan membuka data lokasi ke seluruh user aplikasi.